#!/bin/bash

parentdir=${0%/*}
which perl >/dev/null 2>&1
if [ "$?" ] ; then
	distro=`perl $parentdir/linux_distro 2>&1`
else
	distro="not available (couldn't find perl)"
fi

echo "distribution: $distro"

detail=`uname -a`
echo "uname: $detail"

. "$parentdir/desktop_environment"
