#!/bin/sh
#---------------------------------------------
#   xdg-su
#
#   Utility script to run a command as an alternate user, generally
#       the root user
#
#   Refer to the usage() function below for usage.
#
#   Copyright 2006, Jeremy White <jwhite@codeweavers.com>
#   Copyright 2006, Kevin Krammer <kevin.krammer@gmx.at>
#
#   LICENSE:
#
#   Permission is hereby granted, free of charge, to any person obtaining a
#   copy of this software and associated documentation files (the "Software"),
#   to deal in the Software without restriction, including without limitation
#   the rights to use, copy, modify, merge, publish, distribute, sublicense,
#   and/or sell copies of the Software, and to permit persons to whom the
#   Software is furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included
#   in all copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
#   OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
#   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#   OTHER DEALINGS IN THE SOFTWARE.
#
#---------------------------------------------

usage()
{
cat << _USAGE
xdg-su -- run a program as root after prompting for the root password

Synopsis

   xdg-su [--help] [command]

_USAGE
    exit 1
}

su_kde()
{
    kdesu "$*"

    exit $?
}

su_gnome()
{
    gnomesu -c "$*"

    exit $?
}

su_generic()
{
    XSU=`which xsu 2>/dev/null`
    if [ $? -eq 0 ] ; then
        $XSU "$*"

        exit $?
    else
        echo Sorry, no method available for invoking su "$*"
        exit 2
    fi
}

[ "$1" != "" ] || usage
[ "$1" != "--help" ] || usage
[ "${1:0:1}" != "-" ] || usage

#@xdg-utils-common@

#----------------------------------------------------------------------------
#   Common utility functions included in all XDG wrapper scripts
#----------------------------------------------------------------------------
detectDE()
{
    if [ "$KDE_FULL_SESSION" == "true" ]; then DE=kde;
    elif [ "$GNOME_DESKTOP_SESSION_ID" != "" ]; then DE=gnome;
    fi
}

detectDE

#----------------------------------------------------------------------------



case "$DE" in
    kde)
    su_kde "$*"
    ;;

    gnome)
    su_gnome "$*"
    ;;

    *)
    su_generic "$*"
    ;;
esac
