// File autogenerated

#if !defined(DAPI_H_INCLUDED)
#define DAPI_H_INCLUDED

// Qt D-Bus includes
#include <dbus/qdbusobject.h>

// forward declarations
class QDBusError;
class QDBusVariant;
class QString;
class QStringList;

namespace org
{
namespace freedesktop
{

class dapi : public QDBusObjectBase
{
public:
    virtual ~dapi() {}

protected:

    virtual bool Capabilities(Q_INT32& capabilities, QDBusError& error) = 0;

    virtual bool OpenUrl(const QString& url, const QDBusVariant& windowinfo, QDBusError& error) = 0;

    virtual bool ExecuteUrl(const QString& url, const QDBusVariant& windowinfo, QDBusError& error) = 0;

    virtual bool ButtonOrder(Q_INT32& order, QDBusError& error) = 0;

    virtual bool RunAsUser(const QString& user, const QString& command, const QDBusVariant& windowinfo, QDBusError& error) = 0;

    virtual bool SuspendScreenSaving(Q_UINT32 client_id, bool suspend, QDBusError& error) = 0;

    virtual bool MailTo(const QString& subject, const QString& body, const QString& to, const QString& cc, const QString& bcc, const QStringList& attachments, const QDBusVariant& windowinfo, QDBusError& error) = 0;

    virtual bool LocalFile(const QString& url, const QString& local, bool allow_download, QString& filename, const QDBusVariant& windowinfo, QDBusError& error) = 0;

    virtual bool UploadFile(const QString& local, const QString& url, bool remove_local, const QDBusVariant& windowinfo, QDBusError& error) = 0;

    virtual bool RemoveTemporaryLocalFile(const QString& local, QDBusError& error) = 0;

    virtual bool AddressBookList(QStringList& contact_ids, QDBusError& error) = 0;

    virtual bool AddressBookOwner(QString& contact_id, QDBusError& error) = 0;

    virtual bool AddressBookFindByName(const QString& name, QStringList& contact_ids, QDBusError& error) = 0;

    virtual bool AddressBookGetName(const QString& contact_id, QString& given_name, QString& family_name, QString& full_name, QDBusError& error) = 0;

    virtual bool AddressBookGetEmails(const QString& contact_id, QStringList& email_addresses, QDBusError& error) = 0;

    virtual bool AddressBookGetVCard30(const QString& contact_id, QString& vcard, QDBusError& error) = 0;

    virtual void handleMethodReply(const QDBusMessage& reply) = 0;

private:
    QDBusMessage callCapabilities(const QDBusMessage& mesage);

    QDBusMessage callOpenUrl(const QDBusMessage& mesage);

    QDBusMessage callExecuteUrl(const QDBusMessage& mesage);

    QDBusMessage callButtonOrder(const QDBusMessage& mesage);

    QDBusMessage callRunAsUser(const QDBusMessage& mesage);

    QDBusMessage callSuspendScreenSaving(const QDBusMessage& mesage);

    QDBusMessage callMailTo(const QDBusMessage& mesage);

    QDBusMessage callLocalFile(const QDBusMessage& mesage);

    QDBusMessage callUploadFile(const QDBusMessage& mesage);

    QDBusMessage callRemoveTemporaryLocalFile(const QDBusMessage& mesage);

    QDBusMessage callAddressBookList(const QDBusMessage& mesage);

    QDBusMessage callAddressBookOwner(const QDBusMessage& mesage);

    QDBusMessage callAddressBookFindByName(const QDBusMessage& mesage);

    QDBusMessage callAddressBookGetName(const QDBusMessage& mesage);

    QDBusMessage callAddressBookGetEmails(const QDBusMessage& mesage);

    QDBusMessage callAddressBookGetVCard30(const QDBusMessage& mesage);

    virtual bool handleMethodCall(const QDBusMessage& message);
}; // class dapi

}; // namespace freedesktop

}; // namespace org

#endif //DAPI_H_INCLUDED

// End of File

