#!/bin/bash

## Usage:
## testrun dir1 dir2 ... 
## testrun t.foo t.bar ...
## Will find and run all files in dirs that begin with t.*

## Result format:
## dir1/sub/path/t.foo: FAIL: some reason
## dir1/sub/path/t.bar: UNTESTED: some other reason

if [ -z "$XDG_TEST_DIR" ] ; then
	export XDG_TEST_DIR=`pwd`
	echo "WARNING: guessed XDG_TEST_DIR to be $XDG_TEST_DIR"
fi
if [ -d "$XDG_TEST_DIR/../scripts" ] ; then
	export PATH="$PATH:$XDG_TEST_DIR/../scripts"
fi

if [ $# -eq 0 ] ; then
	TEST_GROUPS=`find "$XDG_TEST_DIR" -type d -name 'xdg-*'`
else
	TEST_GROUPS="$@"
fi

TEST_FILES=`find $TEST_GROUPS -name 't.*'`

declare -i PASS=0
declare -i TOTAL=0
TEST_LOG="xdg-test.log"

export USING_TEST_RUNNER="true"

for t in $TEST_FILES; do
	. "$t"
done

echo "[`date`] TEST RUN START: $*" >> "$TEST_LOG"
echo "TEST_LIST: $TEST_LIST"

for t in $TEST_LIST; do
	TOTAL=$((TOTAL + 1 ))

	test_setup

	# Run test - subshell is necessary to keep things contained.
	( "$t") >> "$TEST_LOG"
	CODE="$?"

	test_cleanup

	# Report result
	if [ "$CODE" -eq 0 ] ; then
		PASS=$((PASS + 1))
	else
		case "$CODE" in
		1 ) RESULT=FAIL;;
		5 ) RESULT=UNTESTED;;
		7 ) RESULT=NORESULT;;
		* ) RESULT="UNKNOWN($CODE)";;
		esac
		echo  "$RESULT: $t"
	fi
done
echo -n "[`date`] TEST RUN END: $* - " >> "$TEST_LOG"
echo "$PASS of $TOTAL tests passed." | tee -a "$TEST_LOG"
echo "See $TEST_LOG for details."

if [ $(( $TOTAL - $PASS )) -gt 0 ]; then
	EC=1
	echo "NOT OK!"
else
	EC=0
	echo "ok"
fi
exit "$EC"
